//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ChemProV.Library.OsbleAuthServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/OSBLE.Models.Users")]
    public partial class UserProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AspNetUserNamek__BackingFieldField;
        
        private string AuthenticationHashk__BackingFieldField;
        
        private bool CanCreateCoursesk__BackingFieldField;
        
        private int DefaultCoursek__BackingFieldField;
        
        private bool EmailAllActivityPostsk__BackingFieldField;
        
        private bool EmailAllNotificationsk__BackingFieldField;
        
        private string FirstNamek__BackingFieldField;
        
        private int IDk__BackingFieldField;
        
        private string Identificationk__BackingFieldField;
        
        private bool IsAdmink__BackingFieldField;
        
        private bool IsApprovedk__BackingFieldField;
        
        private string LastNamek__BackingFieldField;
        
        private string Passwordk__BackingFieldField;
        
        private int SchoolIDk__BackingFieldField;
        
        private ChemProV.Library.OsbleAuthServices.School Schoolk__BackingFieldField;
        
        private int SortByk__BackingFieldField;
        
        private string UserNamek__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AspNetUserName>k__BackingField", IsRequired=true)]
        public string AspNetUserNamek__BackingField {
            get {
                return this.AspNetUserNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.AspNetUserNamek__BackingFieldField, value) != true)) {
                    this.AspNetUserNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("AspNetUserNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AuthenticationHash>k__BackingField", IsRequired=true)]
        public string AuthenticationHashk__BackingField {
            get {
                return this.AuthenticationHashk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationHashk__BackingFieldField, value) != true)) {
                    this.AuthenticationHashk__BackingFieldField = value;
                    this.RaisePropertyChanged("AuthenticationHashk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CanCreateCourses>k__BackingField", IsRequired=true)]
        public bool CanCreateCoursesk__BackingField {
            get {
                return this.CanCreateCoursesk__BackingFieldField;
            }
            set {
                if ((this.CanCreateCoursesk__BackingFieldField.Equals(value) != true)) {
                    this.CanCreateCoursesk__BackingFieldField = value;
                    this.RaisePropertyChanged("CanCreateCoursesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DefaultCourse>k__BackingField", IsRequired=true)]
        public int DefaultCoursek__BackingField {
            get {
                return this.DefaultCoursek__BackingFieldField;
            }
            set {
                if ((this.DefaultCoursek__BackingFieldField.Equals(value) != true)) {
                    this.DefaultCoursek__BackingFieldField = value;
                    this.RaisePropertyChanged("DefaultCoursek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EmailAllActivityPosts>k__BackingField", IsRequired=true)]
        public bool EmailAllActivityPostsk__BackingField {
            get {
                return this.EmailAllActivityPostsk__BackingFieldField;
            }
            set {
                if ((this.EmailAllActivityPostsk__BackingFieldField.Equals(value) != true)) {
                    this.EmailAllActivityPostsk__BackingFieldField = value;
                    this.RaisePropertyChanged("EmailAllActivityPostsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EmailAllNotifications>k__BackingField", IsRequired=true)]
        public bool EmailAllNotificationsk__BackingField {
            get {
                return this.EmailAllNotificationsk__BackingFieldField;
            }
            set {
                if ((this.EmailAllNotificationsk__BackingFieldField.Equals(value) != true)) {
                    this.EmailAllNotificationsk__BackingFieldField = value;
                    this.RaisePropertyChanged("EmailAllNotificationsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FirstName>k__BackingField", IsRequired=true)]
        public string FirstNamek__BackingField {
            get {
                return this.FirstNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNamek__BackingFieldField, value) != true)) {
                    this.FirstNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("FirstNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ID>k__BackingField", IsRequired=true)]
        public int IDk__BackingField {
            get {
                return this.IDk__BackingFieldField;
            }
            set {
                if ((this.IDk__BackingFieldField.Equals(value) != true)) {
                    this.IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Identification>k__BackingField", IsRequired=true)]
        public string Identificationk__BackingField {
            get {
                return this.Identificationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Identificationk__BackingFieldField, value) != true)) {
                    this.Identificationk__BackingFieldField = value;
                    this.RaisePropertyChanged("Identificationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsAdmin>k__BackingField", IsRequired=true)]
        public bool IsAdmink__BackingField {
            get {
                return this.IsAdmink__BackingFieldField;
            }
            set {
                if ((this.IsAdmink__BackingFieldField.Equals(value) != true)) {
                    this.IsAdmink__BackingFieldField = value;
                    this.RaisePropertyChanged("IsAdmink__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsApproved>k__BackingField", IsRequired=true)]
        public bool IsApprovedk__BackingField {
            get {
                return this.IsApprovedk__BackingFieldField;
            }
            set {
                if ((this.IsApprovedk__BackingFieldField.Equals(value) != true)) {
                    this.IsApprovedk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsApprovedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastName>k__BackingField", IsRequired=true)]
        public string LastNamek__BackingField {
            get {
                return this.LastNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNamek__BackingFieldField, value) != true)) {
                    this.LastNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("LastNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Password>k__BackingField", IsRequired=true)]
        public string Passwordk__BackingField {
            get {
                return this.Passwordk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Passwordk__BackingFieldField, value) != true)) {
                    this.Passwordk__BackingFieldField = value;
                    this.RaisePropertyChanged("Passwordk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SchoolID>k__BackingField", IsRequired=true)]
        public int SchoolIDk__BackingField {
            get {
                return this.SchoolIDk__BackingFieldField;
            }
            set {
                if ((this.SchoolIDk__BackingFieldField.Equals(value) != true)) {
                    this.SchoolIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("SchoolIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<School>k__BackingField", IsRequired=true)]
        public ChemProV.Library.OsbleAuthServices.School Schoolk__BackingField {
            get {
                return this.Schoolk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Schoolk__BackingFieldField, value) != true)) {
                    this.Schoolk__BackingFieldField = value;
                    this.RaisePropertyChanged("Schoolk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SortBy>k__BackingField", IsRequired=true)]
        public int SortByk__BackingField {
            get {
                return this.SortByk__BackingFieldField;
            }
            set {
                if ((this.SortByk__BackingFieldField.Equals(value) != true)) {
                    this.SortByk__BackingFieldField = value;
                    this.RaisePropertyChanged("SortByk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserName>k__BackingField", IsRequired=true)]
        public string UserNamek__BackingField {
            get {
                return this.UserNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNamek__BackingFieldField, value) != true)) {
                    this.UserNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("UserNamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="School", Namespace="http://schemas.datacontract.org/2004/07/OSBLE.Models")]
    public partial class School : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ID>k__BackingField", IsRequired=true)]
        public int IDk__BackingField {
            get {
                return this.IDk__BackingFieldField;
            }
            set {
                if ((this.IDk__BackingFieldField.Equals(value) != true)) {
                    this.IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="OsbleAuthServices.AuthenticationService")]
    public interface AuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:AuthenticationService/GetActiveUser", ReplyAction="urn:AuthenticationService/GetActiveUserResponse")]
        System.IAsyncResult BeginGetActiveUser(string authToken, System.AsyncCallback callback, object asyncState);
        
        ChemProV.Library.OsbleAuthServices.UserProfile EndGetActiveUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:AuthenticationService/ValidateUser", ReplyAction="urn:AuthenticationService/ValidateUserResponse")]
        System.IAsyncResult BeginValidateUser(string userName, string password, System.AsyncCallback callback, object asyncState);
        
        string EndValidateUser(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationServiceChannel : ChemProV.Library.OsbleAuthServices.AuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetActiveUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetActiveUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ChemProV.Library.OsbleAuthServices.UserProfile Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ChemProV.Library.OsbleAuthServices.UserProfile)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<ChemProV.Library.OsbleAuthServices.AuthenticationService>, ChemProV.Library.OsbleAuthServices.AuthenticationService {
        
        private BeginOperationDelegate onBeginGetActiveUserDelegate;
        
        private EndOperationDelegate onEndGetActiveUserDelegate;
        
        private System.Threading.SendOrPostCallback onGetActiveUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginValidateUserDelegate;
        
        private EndOperationDelegate onEndValidateUserDelegate;
        
        private System.Threading.SendOrPostCallback onValidateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AuthenticationServiceClient() {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetActiveUserCompletedEventArgs> GetActiveUserCompleted;
        
        public event System.EventHandler<ValidateUserCompletedEventArgs> ValidateUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ChemProV.Library.OsbleAuthServices.AuthenticationService.BeginGetActiveUser(string authToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetActiveUser(authToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChemProV.Library.OsbleAuthServices.UserProfile ChemProV.Library.OsbleAuthServices.AuthenticationService.EndGetActiveUser(System.IAsyncResult result) {
            return base.Channel.EndGetActiveUser(result);
        }
        
        private System.IAsyncResult OnBeginGetActiveUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string authToken = ((string)(inValues[0]));
            return ((ChemProV.Library.OsbleAuthServices.AuthenticationService)(this)).BeginGetActiveUser(authToken, callback, asyncState);
        }
        
        private object[] OnEndGetActiveUser(System.IAsyncResult result) {
            ChemProV.Library.OsbleAuthServices.UserProfile retVal = ((ChemProV.Library.OsbleAuthServices.AuthenticationService)(this)).EndGetActiveUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetActiveUserCompleted(object state) {
            if ((this.GetActiveUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetActiveUserCompleted(this, new GetActiveUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetActiveUserAsync(string authToken) {
            this.GetActiveUserAsync(authToken, null);
        }
        
        public void GetActiveUserAsync(string authToken, object userState) {
            if ((this.onBeginGetActiveUserDelegate == null)) {
                this.onBeginGetActiveUserDelegate = new BeginOperationDelegate(this.OnBeginGetActiveUser);
            }
            if ((this.onEndGetActiveUserDelegate == null)) {
                this.onEndGetActiveUserDelegate = new EndOperationDelegate(this.OnEndGetActiveUser);
            }
            if ((this.onGetActiveUserCompletedDelegate == null)) {
                this.onGetActiveUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetActiveUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetActiveUserDelegate, new object[] {
                        authToken}, this.onEndGetActiveUserDelegate, this.onGetActiveUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ChemProV.Library.OsbleAuthServices.AuthenticationService.BeginValidateUser(string userName, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidateUser(userName, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string ChemProV.Library.OsbleAuthServices.AuthenticationService.EndValidateUser(System.IAsyncResult result) {
            return base.Channel.EndValidateUser(result);
        }
        
        private System.IAsyncResult OnBeginValidateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userName = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((ChemProV.Library.OsbleAuthServices.AuthenticationService)(this)).BeginValidateUser(userName, password, callback, asyncState);
        }
        
        private object[] OnEndValidateUser(System.IAsyncResult result) {
            string retVal = ((ChemProV.Library.OsbleAuthServices.AuthenticationService)(this)).EndValidateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidateUserCompleted(object state) {
            if ((this.ValidateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidateUserAsync(string userName, string password) {
            this.ValidateUserAsync(userName, password, null);
        }
        
        public void ValidateUserAsync(string userName, string password, object userState) {
            if ((this.onBeginValidateUserDelegate == null)) {
                this.onBeginValidateUserDelegate = new BeginOperationDelegate(this.OnBeginValidateUser);
            }
            if ((this.onEndValidateUserDelegate == null)) {
                this.onEndValidateUserDelegate = new EndOperationDelegate(this.OnEndValidateUser);
            }
            if ((this.onValidateUserCompletedDelegate == null)) {
                this.onValidateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidateUserCompleted);
            }
            base.InvokeAsync(this.onBeginValidateUserDelegate, new object[] {
                        userName,
                        password}, this.onEndValidateUserDelegate, this.onValidateUserCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ChemProV.Library.OsbleAuthServices.AuthenticationService CreateChannel() {
            return new AuthenticationServiceClientChannel(this);
        }
        
        private class AuthenticationServiceClientChannel : ChannelBase<ChemProV.Library.OsbleAuthServices.AuthenticationService>, ChemProV.Library.OsbleAuthServices.AuthenticationService {
            
            public AuthenticationServiceClientChannel(System.ServiceModel.ClientBase<ChemProV.Library.OsbleAuthServices.AuthenticationService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetActiveUser(string authToken, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = authToken;
                System.IAsyncResult _result = base.BeginInvoke("GetActiveUser", _args, callback, asyncState);
                return _result;
            }
            
            public ChemProV.Library.OsbleAuthServices.UserProfile EndGetActiveUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                ChemProV.Library.OsbleAuthServices.UserProfile _result = ((ChemProV.Library.OsbleAuthServices.UserProfile)(base.EndInvoke("GetActiveUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginValidateUser(string userName, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userName;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("ValidateUser", _args, callback, asyncState);
                return _result;
            }
            
            public string EndValidateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ValidateUser", _args, result)));
                return _result;
            }
        }
    }
}
